### ISSUE TITLE
Remove dirspec dependency

### ISSUE THREAD

**Issue by amcgee** [WellDone/pymomo#11]
It requires --allow-external and --allow-unverified on install, and requires pywin32 on Windows (which isn't easy to install - it's not on PyPi)

**Comment by timburke** [comment]
This shouldn't be too hard.  We just need to find a config directory on each platform we support.  On windows it looks like this should be a subdirectory of %APPDATA%:
http://www.microsoft.com/security/portal/mmpc/shared/variables.aspx
Supported on Windows 2000 and newer

On Mac OS X it should be a directory under:
~/Library/Preferences

On Linux is should be a subdirectory under:
~/.config
Per the XDG base directory spec:
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
